# This is a basic workflow to help you get started with Actions

name: Scryfall In-Memory DB Theory Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        
    - name: Create minimal dbt profiles.yml
      run: |
        mkdir -p /home/runner/.dbt
        echo "ci_duckdb:" > /home/runner/.dbt/profiles.yml
        echo "  target: dev" >> /home/runner/.dbt/profiles.yml
        echo "  outputs:" >> /home/runner/.dbt/profiles.yml
        echo "    dev:" >> /home/runner/.dbt/profiles.yml
        echo "      type: duckdb" >> /home/runner/.dbt/profiles.yml
        echo "      path: ':memory:'" >> /home/runner/.dbt/profiles.yml

    - name: Dbt Compile
      run: |
        dbt compile --project-dir src/mtgv2/defs/dbt_assets
            
    - name: Run pipeline tests
      run: |
        pytest test/scryfall_job_test.py -v --tb=short
    
    - name: Test results
      if: failure()
      run: echo "Tests failed - check the logs above"
